server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PetStore?currentSchema=public
    username: postgres
    password: 193192
    driver-class-name: org.postgresql.Driver
  graphql:
    graphiql:
      enabled: true
  jpa:
    open-in-view: false